### ISSUE TITLE
Adding comment to document creates two posts

### ISSUE THREAD

**Issue by joho1968** [julien-nc/integration_mattermost#11]
Excellent integration! :metal: 

If I choose to add a comment to the file I upload (not sharing link), the integration generates two posts. IMHO, it should generate one post with the text (comment) and an attachment. It makes following a thread very hard since both posts will lack context.

It seems to work differently if I choose to share the link in MM.

**Comment by joho1968** [comment]
> Indeed, sharing the link creates only 1 post, which is good :)

Yes, it is, it's great. My point is that I think **uploading** the file to MM with a comment should **also** only create one post, not two.

**Comment by julien-nc** [comment]
Thanks for the suggestion. Makes total sense and was not so hard-ish to implement.

This is included in [v1.0.3-2-nightly](https://github.com/julien-nc/integration_mattermost/releases/download/v1.0.3-2-nightly/integration_mattermost-1.0.3-2-nightly.tar.gz) if you wanna try it. Otherwise, wait for the next release, coming soon.

**Comment by joho1968** [comment]
Oh, I didn't even try the multiple files variant; yeah, that would have been "odd" to see in action 😳 🤔 

Glad you went "all the way" with this, your implementation sounds exactly like I think it should be done. Great stuff!
